check waf and wafregional stream their logs
bridgecrewio/checkov pull request #1895
Opened 2021-11-03 16:15 UTC by JamesWoolfenden

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
If youve applied a WAF to cloudfront etc you need to see what it is and isnt blocking. Youll need to have logs for that. This ensures you do that.

2021-11-03 17:04 UTC, mikeurbanski1 commented on checkov/terraform/checks/resource/aws/WAFHasLogs.py
> +        name = "Ensure Logging for Web Access Control Lists"
```suggestion
        name = "Ensure Logging is enabled for WAF  Web Access Control Lists"
```

2021-11-04 16:25 UTC, mikeurbanski1 approved these changes

2021-11-04 16:29 UTC, gruebel requested changes

2021-11-04 16:29 UTC, gruebel commented on checkov/terraform/checks/resource/aws/WAFHasLogs.py
> +        supported_resources = ['aws_waf_web_acl', 'aws_wafregional_web_acl', 'aws_wafv2_web_acl']
```suggestion
        supported_resources = ['aws_waf_web_acl', 'aws_wafregional_web_acl']
```
`aws_wafv2_web_acl` has a separate resource for logging, which you added via `CKV2_AWS_31` 😄

2021-11-04 19:24 UTC, gruebel approved these changes
🚀

2021-11-04 19:24 UTC, merged