Add checks for NGINX Ingress CVE-2021-25742
bridgecrewio/checkov pull request #1907
Opened 2021-11-05 16:46 UTC by metahertz

This PR Contains two new Kubernetes checks based on detecting CVE-2021-25742.
(More details on the CVE Here: https://github.com/kubernetes/ingress-nginx/issues/7837).

The first check fails if there are annotations containing configuration snippets **AND** it looks like those snippets contain lua-related directives or access the kubernetes.io secrets/config paths.

The second check is wider, and will fail if there are any annotations related to nginx configuration snippets.

This gives users a choice, as conversations in https://github.com/kubernetes/ingress-nginx/issues/7837 suggest that fully blocking snippets in annotations works well, but for others they need snippets and just want to block lua script directives.

A user could chose which they need by either `--skip-checks CKV_K8S_152` or `--skip-checks CKV_K8S_153` globally on the `checkov` command line, or use the `SKIP_CHECK` annotations for checkov directly in their k8s manifests or helm/kustomize charts.

@eurogig Would love some feedback/other examples for the tests directory if you have anything more creative ;)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-06 20:39 UTC, gruebel requested changes

2021-11-06 20:39 UTC, gruebel commented on checkov/kubernetes/checks/NginxIngressCVE202125742AllSnippets.py
> +        return CheckResult.PASSED
```suggestion
        if conf["metadata"]:
            if conf["metadata"].get('annotations'):
                for annotation in force_list(conf["metadata"]["annotations"]):
                    for key in annotation:
                        if "snippet" in key:
                            return CheckResult.FAILED
        return CheckResult.PASSED
```
There are couple of things
- `conf["metadata"]["annotations"]` is doubled, once is more than enough 😄 
- the last else has no return, and actually is not needed
- the current check, only checks if the first annotation has `snippet` in the name. you can test it by changing the order of the annotations in the passed check
This is how it should look like from my point of view 🙂

2021-11-06 20:39 UTC, gruebel commented on checkov/kubernetes/checks/NginxIngressCVE202125742Lua.py
> +        return CheckResult.PASSED
```suggestion
        if conf["metadata"]:
            if conf["metadata"].get('annotations'):
                for annotation in force_list(conf["metadata"]["annotations"]):
                    for key, value in annotation.items():
                        if "snippet" in key and  re.match(badInjectionPatterns, value):
                            return CheckResult.FAILED
        return CheckResult.PASSED
```
same points as before 🙂

2021-11-08 16:34 UTC, metahertz commented
Added a third check on the following logic after walking through @eurogig's example malicious ingress: 
- The "All snippets" check may be commonly skipped as snippets are a common usecase.
- The LUA check does not prevent abuse of filesystem access using alias configuration.
- The third Alias check is to address this non-lua exploit path

This check will prevent against the following style of abuse:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: developer
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ "/test" {
        default_type 'text/plain';
        alias /var/run;
      }
spec:
  rules:
  - http:
      paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: web
              port:
                number: 8080
```

2021-11-08 16:56 UTC, eurogig commented
Awesome!  This is looking pretty solid!

2021-11-09 17:50 UTC, schosterbarak approved these changes

2021-11-09 17:50 UTC, merged