Add custom policy guidelines to integration
bridgecrewio/checkov pull request #1908
Opened 2021-11-05 19:09 UTC by mikeurbanski1

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Inserts guidelines from the platform when pulling custom checks.

There is supposed to be an API call that returns guidelines for custom checks, but it is not doing so. This works around that more reliably.

2021-11-05 19:18 UTC, kartikp10 approved these changes
Looks good! Pretty sure UTs won't break

2021-11-09 17:53 UTC, schosterbarak requested changes
@mikeurbanski1 please add UT under integration tests directory . We have ones that are running with API key

2021-12-03 21:19 UTC, nimrodkor commented on integration_tests/test_checkov_cli_integration_report.py
> +    def test_guideline_in_custom_policy(self):
@mikeurbanski1 This test should run only when we have the API key, which is embodied in this:
```python
if sys.version_info[1] == 7 and platform.system() == 'Linux':
```

2022-02-27 12:06 UTC, nimrodkor commented
@mikeurbanski1 is this still needed?

2022-03-02 08:57 UTC, closed without merging