Update readme with SCA details
bridgecrewio/checkov pull request #2877
Opened 2022-04-27 11:28 UTC by Saarett

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-27 11:40 UTC, tsmithv11 reviewed
Good additions. Made a few suggestions.

2022-04-27 11:40 UTC, tsmithv11 commented on README.md
> +**Checkov** is a static code analysis tool for infrastructure-as-code and it is also a software-composition-analysis tool for open-source images and packages.
Using dashes is pretty uncommon and we scan closed source images. Suggest:
`**Checkov** is a static code analysis tool for infrastructure as code (IaC) and also a software composition analysis (SCA) tool for images and open source packages.`

2022-04-27 11:40 UTC, tsmithv11 commented on README.md
> +It scans open source packages and images for [Common Vulnerabilities and Exposures](https://cve.mitre.org/)
Can we point to docs instead of MITRE like the other links in this section?

2022-05-23 06:23 UTC, taysmith-test requested changes
Looks good! Added two suggestions

2022-05-23 06:23 UTC, taysmith-test commented on docs/7.Scan Examples/Sca.md
> +Checkov is an SCA (Software Composition Analysis) tool. This means it scans package files closed source images for Common Vulnerabilities and Exposures (CVEs).
Recommend: `Checkov is an SCA (Software Composition Analysis) tool. This means it scans package files and container images for Common Vulnerabilities and Exposures (CVEs).`

2022-05-23 06:23 UTC, taysmith-test commented on docs/7.Scan Examples/Sca.md
> +You can [Find here](https://docs.bridgecrew.io/docs/open-source-vulnerability-scanning) the full list of the supported package manager types.
`You can find the full list of the supported package manager types [here]((https://docs.bridgecrew.io/docs/open-source-vulnerability-scanning).`

2022-05-23 06:41 UTC, merged