feat(terraform): add CKV NCP rule about block storage encryption.
bridgecrewio/checkov pull request #3628
Opened 2022-10-09 05:50 UTC by Floodnut

**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

## Description

Add terraform scan rule about provider Naver Cloud Platform.

CKV_NCP_6 is associated with NCloud Server Encryption.
This rule suggests that base block storage should be encrypted.

### Description
https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest/docs/resources/server

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-21 21:21 UTC, gruebel requested changes
such a check can be easily written by subclassing `BaseResourceValueCheck` instead of `BaseResourceCheck`

2022-10-21 21:21 UTC, gruebel commented on checkov/terraform/checks/resource/ncp/ServerEncryptionVPC.py
> +               " Only support VPC environment."
```suggestion
        name = "Ensure Server instance is encrypted"
```

2022-10-21 21:21 UTC, gruebel commented on checkov/terraform/checks/resource/ncp/ServerEncryptionVPC.py
> +class ServerEncryptionVPC(BaseResourceCheck):
```suggestion
from checkov.terraform.checks.resource.base_resource_value_check import BaseResourceValueCheck


class ServerEncryptionVPC(BaseResourceValueCheck):
```

2022-10-21 21:21 UTC, gruebel commented on checkov/terraform/checks/resource/ncp/ServerEncryptionVPC.py
> +            return CheckResult.FAILED
```suggestion
    def get_inspected_key(self):
        return "is_encrypted_base_block_storage_volume"
```

2022-10-24 06:53 UTC, Floodnut commented
I adjust it!

2022-10-25 09:52 UTC, gruebel commented
please merge master again into your branch, I tried to do it, but got a permission denied

2022-10-25 11:06 UTC, Floodnut commented
> please merge master again into your branch, I tried to do it, but got a permission denied

Oh, sorry. merge this branch again!

2022-10-25 21:53 UTC, gruebel approved these changes
thanks again 🍺

2022-10-26 08:29 UTC, nimrodkor approved these changes

2022-10-26 08:29 UTC, merged