feat(cloudformation): Adding Sse property to SQS Encryption check
bridgecrewio/checkov pull request #5870
Opened 2023-12-14 15:49 UTC by bakosa

**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

This PR enhances the `CKV_AWS_27` check to handle the `SqsManagedSseEnabled` [property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-sqsmanagedsseenabled). 

Note that AWS by [default now enables](https://aws.amazon.com/blogs/compute/announcing-server-side-encryption-with-amazon-simple-queue-service-managed-encryption-keys-sse-sqs-by-default/) SSE to newly created SQS queues. However, this check will still make sure queues are explicitly setting ether KMS or SSE since existing queues won't be encrypted.

I was not sure if we should use a yaml [graph](https://www.checkov.io/3.Custom%20Policies/YAML%20Custom%20Policies.html) based check for this, but I thought re-defining an entire check would be a bit much/have unintended consequences.

Another thing to note is like any `BaseResourceValueCheck` this check won't really handle unknowns if the template is not valid.

Fixes # ([5869](https://github.com/bridgecrewio/checkov/issues/5869))

### Description
Read above

### Fix
*How does someone fix the issue in code and/or in runtime?*
Pass KMS Key ID to encrypt via [KmsMasterKeyId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-kmsmasterkeyid) (which will set SSE to false) or set the [SqsManagedSseEnabled](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-sqsmanagedsseenabled) to `true`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-14 15:56 UTC, bakosa commented
Opened PR for this already https://github.com/bridgecrewio/checkov/pull/5870

2023-12-15 09:23 UTC, JamesWoolfenden requested changes
You need to check what types those properties are, they should be a string and a boolean but they might not be. Other it looks perfect!

2023-12-15 13:21 UTC, bakosa commented
> You need to check what types those properties are, they should be a string and a boolean but they might not be. Other it looks perfect!

Thanks James, I was going to do just that except I was curious what the stance is here in general. If `SqsManagedSseEnabled` is not a bool and `KmsMasterKeyId` is not a string then the resource is not even valid. The `BaseResourceValueCheck` class that this check is currently inheriting from seems like it does not currently check if the `KmsMasterKeyId` is a string/dict or not. I believe if it has ANY value/type except an empty string, it passes" https://github.com/bridgecrewio/checkov/blob/2b58230bb264d4db38dd3b14ce2c2b444790617b/checkov/cloudformation/checks/resource/base_resource_value_check.py#L72


That being said, I will make the updates to check the types and return `CheckResult.UNKNOWN` if those are not as expected?

2023-12-15 13:43 UTC, JamesWoolfenden commented
> > You need to check what types those properties are, they should be a string and a boolean but they might not be. Other it looks perfect!
> 
> Thanks James, I was going to do just that except I was curious what the stance is here in general. If `SqsManagedSseEnabled` is not a bool and `KmsMasterKeyId` is not a string then the resource is not even valid. The `BaseResourceValueCheck` class that this check is currently inheriting from seems like it does not currently check if the `KmsMasterKeyId` is a string/dict/bool/int.. etc or not. I believe if it has ANY value/type except an empty string, it passes"
> 
> https://github.com/bridgecrewio/checkov/blob/2b58230bb264d4db38dd3b14ce2c2b444790617b/checkov/cloudformation/checks/resource/base_resource_value_check.py#L72
> 
> That being said, I will make the updates to check the types and return `CheckResult.UNKNOWN` if those are not as expected?
Yeah id also change the base class BaseResourceCheck and if it fails to parse the fields then its CheckResult.UNKNOWN  and the annotations for scan e.g. ) -> CheckResult: and init  -> None:, and maybe a test case where someone passes something thats not a bool for SqsManagedSseEnabled.

2023-12-15 17:54 UTC, bakosa commented
> > > You need to check what types those properties are, they should be a string and a boolean but they might not be. Other it looks perfect!
> > 
> > 
> > Thanks James, I was going to do just that except I was curious what the stance is here in general. If `SqsManagedSseEnabled` is not a bool and `KmsMasterKeyId` is not a string then the resource is not even valid. The `BaseResourceValueCheck` class that this check is currently inheriting from seems like it does not currently check if the `KmsMasterKeyId` is a string/dict/bool/int.. etc or not. I believe if it has ANY value/type except an empty string, it passes"
> > https://github.com/bridgecrewio/checkov/blob/2b58230bb264d4db38dd3b14ce2c2b444790617b/checkov/cloudformation/checks/resource/base_resource_value_check.py#L72
> > 
> > That being said, I will make the updates to check the types and return `CheckResult.UNKNOWN` if those are not as expected?
> > Yeah id also change the base class BaseResourceCheck and if it fails to parse the fields then its CheckResult.UNKNOWN  and the annotations for scan e.g. ) -> CheckResult: and init  -> None:, and maybe a test case where someone passes something thats not a bool for SqsManagedSseEnabled.

The more I think about this the more I feel like checking for type is inconsistent from what is being done in the [terraform](https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/SQSQueueEncryption.py) check for this same check ID. If I check for whether these properties get a specific type, aren't we just validating the CFT/resource at that point? I don't feel like that makes a whole lot of sense based on the majority of the other checks in here.

2024-01-08 14:44 UTC, JamesWoolfenden commented
if you don't check the types, this valid CFN will pass your check when it should fail:
```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MySourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: "example_arn"
        maxReceiveCount: 5
      SqsManagedSseEnabled: "false"
```

Also i think because the default is now to auto enable SSE your case test_SQSQueueEncryption-FAILED2.yml should now be a pass.

2024-07-02 21:29 UTC, Saarett commented
Hi @bakosa, are you planning to finish the work on this PR? Your efforts are greatly appreciated.

2024-07-15 15:35 UTC, bakosa commented
> Hi @bakosa, are you planning to finish the work on this PR? Your efforts are greatly appreciated.

Yeah, I can take a look this week. I just opened another issue curious thought there too!

2024-08-13 15:40 UTC, bakosa commented
Finally got back to this and pushed updates suggested by @JamesWoolfenden

2025-01-12 13:41 UTC, MaryArmaly commented
Hey @bakosa,
Could you please update your branch with the main branch? Thanks!

2025-08-10 06:55 UTC, pazbechor commented
Closing this for now due to inactivity. Please feel free to reopen it and merge the latest changes from main if you'd like to proceed 🙏

2025-08-10 06:55 UTC, pazbechor commented
Closing this for now due to inactivity. Please feel free to reopen it and merge the latest changes from main if you'd like to proceed 🙏

2025-08-10 06:55 UTC, closed without merging