Update resource-scans.md
bridgecrewio/checkov pull request #620
Opened 2020-10-21 09:05 UTC by powershellpr0mpt

fixed missing trailing single quote
Ensure PostgreSQL database 'log_temp_files flag is set to '0'  
to
Ensure PostgreSQL database 'log_temp_files' flag is set to '0'

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-22 11:03 UTC, angatha approved these changes

2020-10-22 15:32 UTC, schosterbarak commented
hi @powershellpr0mpt the docs are auto generated from the class attributes. I believe you will have to update the text here:
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogTemp.py#L7 for that to work

2020-10-25 05:39 UTC, schosterbarak commented
hey @powershellpr0mpt i see the commit updating the python file, but for some reason the only file changed is the markdown one. do you mind opening a new PR with the updated commit?

2020-10-25 05:43 UTC, schosterbarak requested changes
hey @powershellpr0mpt i see the commit updating the python file, but for some reason the only file changed is the markdown one. do you mind opening a new PR with the updated commit?

2020-11-04 22:39 UTC, closed without merging