In toto output format
bridgecrewio/checkov pull request #6488
Opened 2024-06-24 12:04 UTC by SaraWeinberg1234

**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    Be aware that we use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Additionally a scope is needs to be added to the prefix, which indicates the targeted framework, in doubt choose 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

in-toto Attestation

### Description
Added output of in-toto Attestation format

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-26 08:16 UTC, matansha commented
Hi @SaraWeinberg1234, Thanks for your contribution, please add some tests

2024-07-15 13:59 UTC, ChanochShayner commented
Looks good to me!
@tsmithv11 Could you please review it?
Thx.

2024-07-16 04:38 UTC, tsmithv11 requested changes
It's a good start, but a lot of fields are hard-coded but shouldn't be and there are more fields that could be used.

2024-07-16 04:38 UTC, tsmithv11 commented on checkov/common/output/in_toto_output.py
> +                        "sha256": "fe4fe40ac7250263c5dbe1cf3138912f3f416140aa248637a60d65fe22c47da4"
I believe this should be calculated not static

2024-07-16 04:38 UTC, tsmithv11 commented on checkov/common/output/in_toto_output.py
> +                in_toto_data["predicate"]["invocation"]["builder.id"] = "GitHub Actions"
This should be based on the use of Checkov not static

2024-07-16 04:38 UTC, tsmithv11 commented on checkov/common/output/in_toto_output.py
> +                in_toto_data["predicate"]["invocation"]["uri"] = "https://github.com/developer-guy/alpine/actions/runs/1071875574"
I believe this should not be static

2024-07-16 04:38 UTC, tsmithv11 commented on checkov/common/output/in_toto_output.py
> +                in_toto_data["predicate"]["scanner"]["uri"] = "pkg:github/aquasecurity/trivy@244fd47e07d1004f0aed9"
This should be Checkov not Trivy and the version should not be static

2024-07-16 04:38 UTC, tsmithv11 commented on checkov/common/output/in_toto_output.py
> +                            "method": "nvd",
```suggestion
                            "method": "vendor",
```

2025-01-15 08:19 UTC, MaryArmaly commented
Hey @SaraWeinberg1234,
Could you please merge the latest changes from the main branch into your branch? Thanks!

2025-07-29 16:03 UTC, closed without merging