feat: add support for awscc provider secrets check
bridgecrewio/checkov pull request #6647
Opened 2024-08-09 21:31 UTC by quixoticmonk

**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    We use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the other types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Each prefix should be accompanied by a scope that specifies the targeted framework. If uncertain, use 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

The PR intends to extend the CKV_AWS_41 to have an AWSCC variant to the support the provider. Since the IDs have to be unique, I have currently kept it to be CKV_AWSCC_41 with the assumption that the rules are based on the provider and not the target platform.

## New/Edited policies (Delete if not relevant)

- [NEW] : CKV_AWSCC_41 : "Ensure no hard coded AWS access key and secret key exists in provider"

### Description
The rule maps back to the way a provider is configured to work with AWS. 

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my feature, policy, or fix is effective and works
- [X] New and existing tests pass locally with my changes

2025-01-05 13:37 UTC, AdamDev commented on checkov/terraform/checks/provider/awscc/credentials.py
> +        id = "CKV_AWSCC_41"
This check already exists, with ID:
CKV_AWS_41

2025-01-05 13:43 UTC, AdamDev commented on checkov/terraform/checks/provider/awscc/credentials.py
> +        supported_provider = ["awscc"]
@tsmithv11 , your review is needed for this provider `AWSCC`.

2025-01-15 08:35 UTC, MaryArmaly commented
Hey @quixoticmonk,
Could you please merge the latest changes from the main branch into your branch? Thanks!

2025-01-15 21:58 UTC, tsmithv11 requested changes
Thanks for the contribution! Can you please merge main into your branch and make the suggested updates so we can run the tests?

2025-01-15 21:58 UTC, tsmithv11 commented on checkov/terraform/checks/provider/awscc/credentials.py
> +        id = "CKV_AWSCC_41"
```suggestion
        id = "CKV_AWS_41"
```
The middle value is the service provider

2025-01-15 21:58 UTC, tsmithv11 commented on tests/terraform/checks/provider/awscc/test_credentials.py
> +    def test_success_empty(self):
Can you use the new testing format like this: https://github.com/bridgecrewio/checkov/blob/5e366b0107c5312fcc610f992dc49e5d245e9e06/tests/terraform/checks/module/registry/test_ModuleCheck.py

2025-03-06 09:10 UTC, quixoticmonk commented on tests/terraform/checks/provider/awscc/test_credentials.py
> +    def test_success_empty(self):
Updated to use a reference file and assertions as in other examples.  The changes from main are merged in.

2025-08-05 12:02 UTC, AdamDev commented
Hey @quixoticmonk,
Could you please merge the latest changes from the main branch into your branch? Thanks!

2025-08-10 10:50 UTC, pazbechor commented
Hey, notice that this check is actually exists in the secrets framework (`CKV_SECRET_2`)
What is the difference?

2025-08-10 10:52 UTC, pazbechor commented
Hey @quixoticmonk, I noticed this check already exists in the secrets framework (CKV_SECRET_2).
Could you clarify what makes this one different?
I’m closing this PR for now - happy to reopen if you think otherwise 🙏

2025-08-10 10:52 UTC, closed without merging

2025-08-10 14:58 UTC, quixoticmonk commented
@pazbechor I was porting over  AWS provider's credential check while the CKV_SECRET_2 seems to be checking for access key/secrey key anywhere. Does it make the AWS provider one redundant too on the provider configuration ?