fix(terraform): Update CKV_AZURE_164 to correct check on trust policy
bridgecrewio/checkov pull request #6757
Opened 2024-10-08 13:17 UTC by paddymorgan84

# User description
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

[//]: # "
    # PR Title
    We use the title to create changelog automatically and therefore only allow specific prefixes
    - break:    to indicate a breaking change, this supersedes any of the other types
    - feat:     to indicate new features or checks
    - fix:      to indicate a bugfix or handling of edge cases of existing checks
    - docs:     to indicate an update to our documentation
    - chore:    to indicate adjustments to workflow files or dependency updates
    - platform: to indicate a change needed for the platform
    Each prefix should be accompanied by a scope that specifies the targeted framework. If uncertain, use 'general'.
    #    
    Allowed prefixs:
    ansible|argo|arm|azure|bicep|bitbucket|circleci|cloudformation|dockerfile|github|gha|gitlab|helm|kubernetes|kustomize|openapi|sast|sca|secrets|serverless|terraform|general|graph|terraform_plan|terraform_json
    #
    ex.
    feat(terraform): add CKV_AWS_123 to ensure that VPC Endpoint Service is configured for Manual Acceptance
"

## Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes # (issue)

## New/Edited policies (Delete if not relevant)

### Description
*Include a description of what makes it a violation and any relevant external links.*

### Fix
*How does someone fix the issue in code and/or in runtime?*

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes

---

# Generated description

Below is a concise technical summary of the changes proposed in this PR:
<p>Update the <code>ACRUseSignedImages</code> class to correct the trust policy check for Azure Container Registries. Modify the <code>scan_resource_conf</code> method to accurately evaluate the <code>trust_policy_enabled</code> and <code>trust_policy/enabled</code> keys, ensuring that the check passes only when the trust policy is enabled. Adjust the test cases in <code>test_ACRUseSignedImages.py</code> to reflect these changes, ensuring that both new and old configurations are tested for compliance.</p>
    <table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6757?tool=ast&topic=Test+Case+Update>Test Case Update</a>
        </td><td>Update test cases to validate the new trust policy logic in Azure Container Registry configurations.<details><summary>Modified files (3)</summary><ul><li>tests/terraform/checks/resource/azure/test_ACRUseSignedImages.py</li>
<li>tests/terraform/checks/resource/azure/example_ACRUseSignedImages/main.tf</li>
<li>tests/terraform/checks/resource/azure/example_ACRGeoreplicated/main.tf</li></ul></details><details><summary>Latest Contributors(2)</summary><table><tr><th>User</th><th>Commit</th><th>Date</th></tr><tr><td>patrickmorgan1984@gmai...</td><td>fix-terraform-Update-C...</td><td>November 27, 2024</td></tr>
<tr><td>JamesWoolfenden</td><td>feat-terraform-new-azu...</td><td>December 28, 2022</td></tr></table></details></td></tr>
<tr><td><a href=https://baz.co/changes/bridgecrewio/checkov/6757?tool=ast&topic=Trust+Policy+Fix>Trust Policy Fix</a>
        </td><td>Correct the trust policy check in <code>ACRUseSignedImages</code> to ensure accurate evaluation of Azure Container Registry configurations.<details><summary>Modified files (1)</summary><ul><li>checkov/terraform/checks/resource/azure/ACRUseSignedImages.py</li></ul></details><details><summary>Latest Contributors(2)</summary><table><tr><th>User</th><th>Commit</th><th>Date</th></tr><tr><td>patrickmorgan1984@gmai...</td><td>fix-terraform-Update-C...</td><td>November 27, 2024</td></tr>
<tr><td>JamesWoolfenden</td><td>feat-terraform-Azure-u...</td><td>November 27, 2022</td></tr></table></details></td></tr></table>This pull request is reviewed by Baz. Join @paddymorgan84 and the rest of your team on <a href=https://baz.co/login>(Baz)</a>.

2024-11-14 06:04 UTC, tsmithv11 requested changes

2024-11-14 06:04 UTC, tsmithv11 commented on checkov/terraform/checks/resource/azure/ACRUseSignedImages.py
> -        return "trust_policy/[0]/enabled"
Thanks @paddymorgan84! Same comment here. This is very helpful and greatly appreciated, but please keep it backwards compatible by checking for either configuration.

2024-11-19 23:12 UTC, paddymorgan84 commented
Changes should be ready @tsmithv11, including the lining I missed from the previous PR. I've also raised a PR in `prisma-cloud-docs` to update documentation: https://github.com/hlxsites/prisma-cloud-docs/pull/933

2024-11-21 18:03 UTC, tsmithv11 commented on tests/terraform/checks/resource/azure/example_ACRGeoreplicated/main.tf
Why did you modify this file? Looks unrelated

2024-11-21 18:03 UTC, tsmithv11 commented on checkov/terraform/checks/resource/azure/ACRUseSignedImages.py
Looks good!

2024-11-21 18:53 UTC, paddymorgan84 commented on tests/terraform/checks/resource/azure/example_ACRGeoreplicated/main.tf
I did a quick search on where else `trust_policy` was used and thought it would be worth updating others to match the latest version too. I can remove if this isn't preferable

2024-11-21 21:49 UTC, tsmithv11 commented on tests/terraform/checks/resource/azure/example_ACRGeoreplicated/main.tf
It's not necessary, but since the check associated with that file doesn't look at that field, it shouldn't matter. I'll trigger the UTs to confirm.

2024-11-26 09:55 UTC, paddymorgan84 commented
@tsmithv11 Any suggestions for someone else to review this for me so it's good to merge?

2024-11-27 13:37 UTC, merged