Add CKV_AWS_107 check for aws_ssm_document session type
bridgecrewio/checkov pull request #980
Opened 2021-03-14 17:10 UTC by gruebel

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Adds the encryption in transit part of issue #192. I think it is better to have to different checks, this one and an other for checking if logging is enabled and encrypted, or should it be then 3 checks?

2021-03-16 11:13 UTC, JamesWoolfenden requested changes
Is this conf.get("document_type") == ["Session"]: isnt true should this be a pass?  same for if content isnt found in keys?

2021-03-16 12:45 UTC, gruebel commented
Correct the `document_type` has couple of other possible values and the only relevant for this check is the `Session` one.

Actually the `content` argument for the Terraform resource is mandatory, but checking other implemented checks, it felt like you approach it very conservative, so did I 😄 

And I have an other question, is it possible to parse the `jsonencode()` function from Terraform with checkov somehow?

2021-03-16 13:18 UTC, JamesWoolfenden commented
if i run your check against
`resource "aws_ssm_document" "notsession" {
  name          = "test_document"
  document_type = "Command"

  content = <<DOC
  {
    "schemaVersion": "1.2",
    "description": "Check ip configuration of a Linux instance.",
    "parameters": {

    },
    "runtimeConfig": {
      "aws:runShellScript": {
        "properties": [
          {
            "id": "0.aws:runShellScript",
            "runCommand": ["ifconfig"]
          }
        ]
      }
    }
  }
DOC
}`

It will pass this check when it should be ignored.

2021-03-16 17:29 UTC, gruebel commented
Then the preferred return is `SKIPPED`?

2021-03-17 12:05 UTC, JamesWoolfenden commented
I talked to the source :
UNKNOWN - when we don't know what to return
SKIPPED - should not be used in a check. it is used in the suppression evaluation.
So its Unknown

2021-03-18 08:41 UTC, JamesWoolfenden approved these changes
LGTM

2021-03-18 10:17 UTC, schosterbarak commented
@gruebel CKV_AWS_107 already exists - can you please pull from master and choose the latest ID?

2021-03-18 10:36 UTC, gruebel commented
@schosterbarak I know 😄  that's why I changed it already to `CKV_AWS_112`
 I just didn't update the PR title https://github.com/bridgecrewio/checkov/blob/baf000fcf46f7ae919fc42d1fccfc93c3ac303fa/checkov/terraform/checks/resource/aws/SSMSessionManagerDocumentEncryption.py#L11

2021-03-21 09:11 UTC, merged